# Application Name and Port
spring.application.name=mytube_gateway
server.port=8080

# Enable debug logging for Gateway
logging.level.root=DEBUG

# Eureka Server Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.leaseRenewalIntervalInSeconds=300
eureka.instance.leaseExpirationDurationInSeconds=600

# Configuración del Config Server
spring.main.web-application-type=reactive
spring.cloud.config.enabled=false

# Gateway Routes for Microservices
# Rutas agrupadas para el servicio de Usuarios
spring.cloud.gateway.routes[0].id=MYTUBE_USERS
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/suscriptions/**

# Rutas agrupadas para el servicio de Canales
spring.cloud.gateway.routes[1].id=MYTUBE_CHANNELS
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/channels/**,/playslists/**,/playslist_videos/**

# Rutas agrupadas para el servicio de Videos
spring.cloud.gateway.routes[2].id=MYTUBE_VIDEOS
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/viewingHistory/**,/videos/**,/reactions/**,/comments/**

# Rutas agrupadas para el servicio de Seguridad
spring.cloud.gateway.routes[3].id=MYTUBE_SECURITY
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

