# Application Name and Port
spring.application.name=mytube_gateway
server.port=8080

# Gateway Configuration
spring.cloud.gateway.discovery.locator.enabled=true

# Permitir encabezados de autorización en el Gateway
spring.cloud.gateway.default-filters[0].name=AddRequestHeader
spring.cloud.gateway.default-filters[0].args.Name=Authorization
spring.cloud.gateway.default-filters[0].args.Value=${request.headers.Authorization}

# Enable debug logging for Gateway
logging.level.root=DEBUG

# Eureka Server Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.compatibility-verifier.enabled=false

# Instance Lease Configurations
eureka.instance.leaseRenewalIntervalInSeconds=300
eureka.instance.leaseExpirationDurationInSeconds=600

# Load Balancer Configuration
spring.cloud.loadbalancer.ribbon.enabled=false

# Gateway Routes for Microservices
spring.cloud.gateway.routes[0].id=MYTUBE_USERS
spring.cloud.gateway.routes[0].uri=lb://MYTUBE_USERS
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=MYTUBE_CHANNELS
spring.cloud.gateway.routes[1].uri=lb://MYTUBE_CHANNELS
spring.cloud.gateway.routes[1].predicates[0]=Path=/channels/**

# Rutas agrupadas para el servicio de videos
spring.cloud.gateway.routes[2].id=MYTUBE_VIDEOS
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/viewingHistory/**,/videos/**,/reactions/**,/comments/**

spring.cloud.gateway.routes[3].id=MYTUBE_SECURITY
spring.cloud.gateway.routes[3].uri=lb://MYTUBE_SECURITY
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

# Enable CORS for easier debugging
spring.web.cors.allowed-origin-patterns=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
