spring.application.name=mytube_gateway
server.port=8080

# Gateway Configuration
spring.cloud.gateway.discovery.locator.enabled=true

#Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.compatibility-verifier.enabled=false

# Intervalo de renovacion de la instancia
eureka.instance.leaseRenewalIntervalInSeconds=300
# Tiempo de espera antes de que Eureka considere una instancia como inactiva
eureka.instance.leaseExpirationDurationInSeconds=600

spring.cloud.loadbalancer.ribbon.enabled=false

spring.cloud.gateway.routes[0].id=MYTUBE_USERS
spring.cloud.gateway.routes[0].uri=lb://MYTUBE_USERS
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=MYTUBE_CHANNELS
spring.cloud.gateway.routes[1].uri=lb://MYTUBE_CHANNELS
spring.cloud.gateway.routes[1].predicates[0]=Path=/channels/**

spring.cloud.gateway.routes[2].id=MYTUBE_VIDEOS
spring.cloud.gateway.routes[2].uri=lb://MYTUBE_VIDEOS
spring.cloud.gateway.routes[2].predicates[0]=Path=/videos/**

spring.cloud.gateway.routes[3].id=MYTUBE_SECURITY
spring.cloud.gateway.routes[3].uri=lb://MYTUBE_SECURITY
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**